version: "3.8"
services:
  app:
    build: "app"
    ports:
      - "5000:5000"
    depends_on:
      - postgres
  postgres:
    build: app/database_files
    container_name: postgres_container
    ports:
      - "5432:5432"
    volumes:
      - data1:/var/lib/postgresql/data
    env_file:
      - app/env/postgres.env
volumes:
  data1: