version: "3.8"
services:
  app:
    build: "app"
    container_name: app_container
    ports:
      - "5000:5000"
    depends_on:
      - database
  database:
    build: "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: postgres_container
    ports:
      - "5432:5432"
    volumes:
      - data1:/var/lib/postgresql/data
    env_file:
      - database/env/postgres.env
volumes:
  data1: