version: "3.8"
services:
  app:
    build: "app"
    container_name: flask
    environment:
      - DATABASE_URL=postgresql://postgres:password@database:5432/data
    ports:
      - "5000:5000"
    depends_on:
      - database
  database:
    build: "database"
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: data
